### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-200-fall-2023/single-pile-nim-assignment#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Programming the CARDIAC

- [ ] decoder.cardiac uses the SFT instruction
- [ ] subroutine.cardiac uses the JMP instruction at least twice
- [ ] high_dimension_adder.cardiac uses the JMP instruction at least once
- [ ] high_dimension_adder.cardiac uses the ADD instruction at least twice
- [ ] high_dimension_adder.cardiac uses the SFT instruction at least once
- [ ] nim.cardiac uses the TAC instruction at least once
- [ ] nim.cardiac uses the STO instruction at least once
- [ ] nim.cardiac prints moves and pile contents a sufficient amount of times
- [ ] nim.cardiac uses the SUB instruction at least once
- [ ] nim.cardiac uses the CLA instruction at least once

## Documentation

- [ ] Answer all of the questions in the report

## Percent complete

Based on the checks achieved, this assignment is `0%` complete.
